# workflow name
name: alioss

# 在main分支上有push命令时触发该流程

on:
  push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - name: setup aliyun oss
              uses: manyuanrong/setup-ossutil@v3.0
              with:
                  endpoint: "oss.aliyuncs.com"
                  access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                  access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
            - name: cp files to aliyun
              run: ossutil cp -ruf public oss://mumukehao/ # 将xxxxx改为创建的Bucket名称，-rf表示覆盖
              
              

